### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-fiscal-rule#32]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] account_fiscal_position_rule_sale
- [ ] account_fiscal_position_rule
- [ ] account_fiscal_position_rule_purchase
- [x] account_product_fiscal_classification - #46
- [ ] account_fiscal_position_rule_stock

**Comment by mbcosta** [comment]
Hi,
   I'm working on account_fiscal_position_rule. I will push it soon.

**Comment by mbcosta** [comment]
I pushed two PR https://github.com/OCA/account-fiscal-rule/pull/45 and https://github.com/OCA/account-fiscal-rule/pull/46, I'm working on other modules and in the next week I'll be able to send the remaining PRs
