### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-fiscal-rule#325]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_avatax_exemption - By @AlexPForgeFlow - #375
- [ ] account_avatax_oca
- [ ] account_avatax_sale_oca
- [x] account_fiscal_position_autodetect_optional_vies - By @ACheung-FactorLibre - #406
- [x] account_fiscal_position_partner_type - By @RodrigoBM - #340
- [x] account_fiscal_position_type - By @legalsylvain - #328
- [x] account_product_fiscal_classification - By @legalsylvain - #327
- [x] account_repair_oca - By @kobros-tech - #461
- [x] l10n_eu_oss_oca - By @ljsalvatierra-factorlibre - #348

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by RodrigoBM** [comment]
Migration account_fiscal_position_partner_type module from v15 PR https://github.com/OCA/account-fiscal-rule/pull/340

**Comment by Nikul-OSI** [comment]
account_avatax_oca #347

**Comment by ljsalvatierra-factorlibre** [comment]
Hi

I'm currently working on migratin `l10n_eu_oss_oca`.

---

https://github.com/OCA/account-fiscal-rule/pull/348

**Comment by ljsalvatierra-factorlibre** [comment]
Hi, could anyone update the issue with #340, #347 and #348 ?

**Comment by ghost** [comment]
Hi,

I'm currently working on migrating `account_fiscal_position_autodetect_optional_vies`.

https://github.com/OCA/account-fiscal-rule/pull/406
