### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-fiscal-rule#55]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_fiscal_position_rule - By @yk2kus - #61 
- [x] account_fiscal_position_rule_purchase - By @renatonlima - #72 
- [x] account_fiscal_position_rule_sale - By @renatonlima - #71 
- [ ] account_fiscal_position_rule_stock - By @mbcosta - #90 
- [x] account_product_fiscal_classification - By @renatonlima - #74
