### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-fiscal-rule#67]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_fiscal_position_rule - By @hugosantosred - #78 
- [ ] account_fiscal_position_rule_purchase - By @Tonow-c2c - #81 
- [ ] account_fiscal_position_rule_sale - By @hugosantosred - #79 
- [ ] account_fiscal_position_rule_stock
- [ ] account_product_fiscal_classification

**Comment by hugosantosred** [comment]
* The PR for account_fiscal_position_rule is in #78 
* The PR for account_fiscal_position_rule_sale is in #79 (But CI is failing because account_fiscal_position_rule is not in that PR)
